const Skills =[
       "Web Development",
      "Mobile App Development",
      "Frontend Development",
      "Backend Development",
      "Full-Stack Development",
      "UI/UX Design",
      "Software Development",
      "Game Development",
      "Blockchain Development",
      "Smart Contracts",
      "Cybersecurity",
      "Cloud Computing",
      "DevOps",
      "Database Management",
      "API Development",
      "WordPress Development",
      "Shopify Development",
      "E-commerce Development",
      "SaaS Development",
      "AR/VR Development",
      "Machine Learning",
      "Artificial Intelligence",
      "Data Science",
      "Django",
      "Express.js",
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "Firebase",
      "AWS",
      "Docker",
      "Git",
      "Figma",
      "Adobe XD",
      "Photoshop",
       "Mobile Development",
         "Flutter",
           "React Native",
      "Data Analysis",
      "Python Programming",
      "JavaScript Development",
      "React.js Development",
      "Node.js Development",
      "PHP Development",
      "Java Development",
      "C++ Development",
      "C# Development",
      "Go (Golang) Development",
      "Ruby on Rails Development",
      "Kotlin Development",
      "Swift (iOS) Development",
      "Android Development",
      "Flutter Development",
      "Rust Development",
      "Penetration Testing",
      "Ethical Hacking",
      "Bug Bounty Research",
      "IoT Development",
      "Embedded Systems",
      "Firmware Development",
      "Robotics Programming",
      "MATLAB",
      "Simulations & Modeling",
      "QA Testing / Software Testing",
      "Automation Scripting",
      "Web Scraping",
      "Chatbot Development",
      "API Integration",
      "CRM Development (Salesforce, HubSpot, Zoho)",
      "ERP Development (SAP, Oracle, Odoo)",
      "Game Design (Unity, Unreal Engine)",
      "Database Optimization",
      "Big Data Engineering",
      "Cloud Architecture (AWS, Azure, GCP)",
      "Server Management",
      "Linux System Administration",
      "Network Administration",
      "IT Support",
      "Graphic Design",
      "Logo Design",
      "Illustration",
      "Print Design",
      "Business Card Design",
      "Flyer & Brochure Design",
      "Poster Design",
      "Infographic Design",
      "UI/UX Wireframing",
      "Product Design",
      "Industrial Design",
      "Fashion Design",
      "Jewelry Design",
      "Interior Design",
      "Architecture Design",
      "3D Modeling",
      "3D Rendering",
      "Animation (2D/3D)",
      "Motion Graphics",
      "Character Design",
      "Video Editing",
      "Photography",
      "Photo Editing / Retouching",
      "Image Manipulation",
      "NFT Art",
      "Storyboarding",
      "T-shirt Design",
      "Merchandise Design",
      "Packaging Design",
      "Label Design",
      "Tattoo Design",
      "Book Cover Design",
      "Album Cover Design",
      "Presentation Design (PowerPoint, Keynote)",
      "Infographic Video Creation",
      "Architectural Visualization",
      "Landscape Design",
      "Set Design (Theater/Film)",
      "Story Illustration",
      "Typography Design",
      "Calligraphy",
      "Comic / Manga Art",
      "Caricature Drawing",
      "Content Writing",
      "Copywriting",
      "Creative Writing",
      "Technical Writing",
      "Blog Writing",
      "Ghostwriting",
      "Script Writing (Film/Video)",
      "Resume Writing",
      "Cover Letter Writing",
      "White Papers",
      "Academic Writing",
      "Research Writing",
      "Proofreading & Editing",
      "Grant Writing",
      "eBook Writing",
      "Speech Writing",
      "Song Lyrics Writing",
      "Product Descriptions",
      "Ad Copywriting",
      "Case Studies",
      "UX Writing",
      "Press Releases",
      "Medical Writing",
      "Legal Writing",
      "Grant Proposals",
      "Business Proposals",
      "Newsletter Writing",
      "Review Writing (Books, Products, Movies)",
      "Social Media Captions",
      "Digital Marketing",
      "SEO (Search Engine Optimization)",
      "SEM (Search Engine Marketing)",
      "Social Media Marketing",
      "Social Media Management",
      "Influencer Marketing",
      "Content Marketing",
      "Email Marketing",
      "Affiliate Marketing",
      "PPC Campaigns (Google, Facebook Ads)",
      "Marketing Strategy",
      "Brand Strategy",
      "Lead Generation",
      "Sales Funnel Design",
      "PR (Public Relations)",
      "Voice Over",
      "Music Production",
      "Audio Editing",
      "Podcast Editing",
      "Sound Design",
      "DJ Services",
      "Singing / Songwriting",
      "Acting",
      "Dance Choreography",
      "Comedy / Stand-up",
      "Video Production",
      "Storytelling",
      "Modeling",
      "Event Hosting",
      "Translation (All Languages)",
      "Transcription",
      "Subtitling / Captioning",
      "Language Tutoring",
      "Localization Services",
      "Sign Language",
      "Online Tutoring",
      "Test Preparation (SAT, IELTS, GRE, etc.)",
      "Academic Coaching",
      "Career Counseling",
      "Life Coaching",
      "Personal Development",
      "E-learning Course Creation",
      "Educational Content Writing",
      "Corporate Training",
      "Virtual Assistant",
      "Data Entry",
      "Customer Support",
      "Technical Support",
      "Project Management",
      "Business Consulting",
      "Financial Consulting",
      "Accounting & Bookkeeping",
      "HR & Recruiting",
      "Market Research",
      "Business Plan Writing",
      "Grant Proposal Writing",
      "Legal Writing",
      "Contract Drafting",
      "Intellectual Property",
      "Business Law",
      "Tax Law",
      "Immigration Law",
      "Paralegal Services",
      "CAD Design",
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Architecture",
      "Structural Engineering",
      "Product Engineering",
      "Lifestyle Coaching",
      "Fitness Training",
      "Nutrition Coaching",
      "Cooking Lessons",
      "Travel Planning",
      "Astrology Services",
      "Gaming Coaching (eSports)",
      "Online Therapy / Counseling",
      "Others",
    
]